# Generated by Django 5.2.1 on 2025-05-27 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('r&n', 'R&D'), ('it', 'IT'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('procurement', 'Procurement')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
