# Generated by Django 5.2.1 on 2025-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_remove_userprofile_fullname_userprofile_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
