# Generated by Django 5.2.1 on 2025-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_inventory_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assigned_to',
            field=models.CharField(choices=[('johndoe', 'John Doe'), ('janedoe', 'Jane Doe'), ('alicewong', 'Alice Wong'), ('bobsmith', 'Bob Smith'), ('charlielee', 'Charlie Lee'), ('dianatan', 'Diana Tan'), ('ericng', 'Eric Ng'), ('fionalim', 'Fiona Lim'), ('georgeho', 'George Ho'), ('hannahcho', 'Hannah Cho'), ('none', 'None')], default='other', max_length=255, verbose_name='Assigned to who?'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('stationery', 'Stationery'), ('computer_accesories', 'Computer Accesories'), ('operational_equiment', 'Operational Equiment'), ('r&d_equipment', 'R&D Equipment'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used'), ('needs_repair', 'Needs Repair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('scrap', 'Scrap')], default='good', max_length=50, verbose_name='Asset condition'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='d_o_p',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Purchase (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('reception', 'Reception'), ('sales department', 'Sales Department'), ('r&d department', 'R&D Department'), ('it department', 'IT department'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=255, verbose_name='Item present location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchased price'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
