# Generated by Django 5.2.1 on 2025-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_inventory_assigned_to_alter_inventory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='null', max_length=255, verbose_name='Item name'),
        ),
    ]
