# Generated by Django 5.2.1 on 2025-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assigned_to',
            field=models.CharField(choices=[('none', 'None'), ('johndoe', 'John Doe'), ('janedoe', 'Jane Doe'), ('alicewong', 'Alice Wong'), ('bobsmith', 'Bob Smith'), ('charlielee', 'Charlie Lee'), ('dianatan', 'Diana Tan'), ('ericng', 'Eric Ng'), ('fionalim', 'Fiona Lim'), ('georgeho', 'George Ho'), ('hannahcho', 'Hannah Cho')], default='other', max_length=255, verbose_name='Assigned to who?'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('reception', 'Reception'), ('sales_department', 'Sales Department'), ('r&d_department', 'R&D Department'), ('it_department', 'IT department'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=255, verbose_name='Item present location'),
        ),
    ]
