# Generated by Django 5.2.1 on 2025-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_inventory_assigned_to_alter_inventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assigned_to',
            field=models.CharField(choices=[('null', 'null'), ('johndoe', 'John Doe'), ('janedoe', 'Jane Doe'), ('alicewong', 'Alice Wong'), ('bobsmith', 'Bob Smith'), ('charlielee', 'Charlie Lee'), ('dianatan', 'Diana Tan'), ('ericng', 'Eric Ng'), ('fionalim', 'Fiona Lim'), ('georgeho', 'George Ho'), ('hannahcho', 'Hannah Cho')], default='other', max_length=255, verbose_name='Assigned to who?'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='intended_usage',
            field=models.CharField(choices=[('null', 'null'), ('sales', 'Sales'), ('operation', 'Operation'), ('r&d', 'R&D'), ('software_development', 'Software Development'), ('management', 'Management'), ('other', 'Other')], default='null', max_length=255, verbose_name='Purpose of assigned item'),
        ),
    ]
