# Generated by Django 5.2.1 on 2025-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_alter_inventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='intended_usage',
            field=models.CharField(choices=[('null', 'null'), ('sales', 'Sales'), ('operation', 'Operation'), ('r&d', 'R&D'), ('software_development', 'Software Development'), ('administration', 'Administration'), ('other', 'Other')], default='null', max_length=255, verbose_name='Purpose of assigned item'),
        ),
    ]
