# Generated by Django 5.2.1 on 2025-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_alter_inventory_intended_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='intended_usage',
            field=models.CharField(choices=[('null', 'null'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('sales', 'Sales'), ('operation', 'Operation'), ('r&d', 'R&D'), ('software_development', 'Software Development'), ('administration', 'Administration'), ('other', 'Other')], default='null', max_length=255, verbose_name='Purpose of assigned item'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('executive_office', 'Executive Office'), ('hr_department', 'HR Department'), ('finance_department', 'Finance Department'), ('sales_department', 'Sales Department'), ('r&d_department', 'R&D Department'), ('it_department', 'IT department'), ('reception', 'Reception'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=255, verbose_name='Item present location'),
        ),
    ]
